package org.example.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data // Lombok to generate getters, setters, equals, hashCode, and toString
@NoArgsConstructor // Lombok to generate a no-argument constructor
@AllArgsConstructor // Lombok to generate a constructor with all fields
public class DoctorResponseDTO {
    private Long id; // The unique ID generated by the database
    private String name;
    private String specialization;
    private String email;
    private String phone;
    // We can add more fields here later without changing our Doctor entity,
    // which gives us a lot of flexibility.
}